### ISSUE TITLE
关于实验结果，跑作者三个月前上传的新数据集

### ISSUE THREAD

**Issue by 30CodeMaker** [MingshiYan/CRGCN#10]
我git下来作者的代码跑作者的数据集，实验结果与论文上的相差挺大的，所有参数都试了，发现有好多组参数的实验结果比论文上的好百分之50以上，这是什么原因没搞清楚，希望作者能够赐教

**Comment by 30CodeMaker** [comment]
.

**Comment by MingshiYan** [comment]
论文中针对Jdata数据集并没有刻意调参。所以你跑出来结果比原文好很正常。

**Comment by 30CodeMaker** [comment]
好的，谢谢作者的回复！btw，请问作者有Tmall和Jdata的原始数据的文件吗，因为查看到data文件夹中的文件似乎不是最原始的数据文件，validation.txt和test.txt文件是初始存在的，想知道作者对原始的数据是如何处理的，jdata数据集那个链接似乎失效了。再次感谢作者的回复！

**Comment by MingshiYan** [comment]
抱歉，我拿到的数据集就是处理好的。已经划分了测试集和验证集。

**Comment by 30CodeMaker** [comment]
好的，谢谢作者！
