### ISSUE TITLE
关于BeiBei数据集与模型性能的问题

### ISSUE THREAD

**Issue by DuTim** [MingshiYan/CRGCN#3]
你好，非常感谢您的工作和开源代码！我对代码中存在几个疑问：
1. 在我的观察中，Tmall 数据中 all.txt 中表示了全部的训练样本。随后将all.txt 分割为 train， valid，test。
<img  src="https://github.com/MingshiYan/CRGCN/assets/50939742/5ff7412c-4407-4566-a2d3-915393e82bd6" width="180" height="">![image](https://github.com/MingshiYan/CRGCN/assets/50939742/00c46833-999d-4f73-871e-1323e0c7dfdd)![image](https://github.com/MingshiYan/CRGCN/assets/50939742/16d3bf47-4e5b-4bae-9f66-1caaf871dbbb)
而在我获得的beibei数据集中，并没有发现验证集，这是否是正常情况？如果在原始数据集中没有验证集，我想了解一下按照怎样的规则（比例）来划分生成验证集。
2. 我在jdata数据上进行超参数的调整，来复现您文中的实验效果。主要调整的参数为[lr, reg_weight]，但是获得的实验效果仍存在巨大的差异，我最优的实验效果如图。能否给一些建议在jdata的参数调整上，来复现您文中的实验效果。
![image](https://github.com/MingshiYan/CRGCN/assets/50939742/37a521e4-d6ce-4c68-a3b1-b78b8d0dd387)
3. 在您的参数注册位置，存在部分没有使用的参数定义，如 node_dropout, message_dropout,在model_cascade.py中没有被使用，这两个dropout操作是否是模型的一部分？
![image](https://github.com/MingshiYan/CRGCN/assets/50939742/1a330d8e-b018-4166-a292-03751562b52e)
![image](https://github.com/MingshiYan/CRGCN/assets/50939742/14d2ecdb-b38e-415b-9e0b-c3ba60dfab20)

非常感谢~~:beers::beers:

**Comment by MingshiYan** [comment]
你好，关于问题1，beibei数据集我发现原作者提供的数据集中validation与test是重复的，因此我就自己将train中每个用户交互的最后一个item取出构造成了validation数据集。
关于问题2，如果设置（比如embedding size等等）没有出现问题的话，建议grid search中增加lr的搜索范围。
关于问题3，node_dropout, message_dropout是用于提升模型泛化能力的，并不是模型的一部分。
希望能够解决你的问题。
