### ISSUE TITLE
找不到data_process.py

### ISSUE THREAD

**Issue by 30CodeMaker** [MingshiYan/CRGCN#8]
作者您好，我在您的仓库找不到您的数据处理的代码即data_process.py，我想看看您是如何处理数据集的，请问可以公开一下吗，或者可以发送到我的邮箱 gjiahao2022@163.com ，谢谢！

**Comment by MingshiYan** [comment]
data_process.py再data.zip里面

**Comment by 30CodeMaker** [comment]
好的，找到了，谢谢作者！

**Comment by 30CodeMaker** [comment]
还有一个问题，作者大大，就是我在data.zip只看到了Tmall、Tmall_cold_all还有jdata，没有找到Beibei的数据集以及数据处理的代码，可以提供一下吗作者大大，感激不尽！
