### ISSUE TITLE
作者大大可以提供一下跑京东数据集的参数设置吗 

### ISSUE THREAD

**Issue by 30CodeMaker** [MingshiYan/CRGCN#9]
我调参数调了好几次达不到论文中差不多的效果 都是差很多  论文中HR@10是0.5001，我跑出来的总是在0.3几

**Comment by MingshiYan** [comment]
重新下载一下数据集看看，前两天更新了数据集

**Comment by 30CodeMaker** [comment]
好的，解决了，跑出来效果就与原论文差一点点，差不多一致，谢谢作者！！！

**Comment by 0yuanxi0** [comment]
你好，我下载的是最新的文件，为啥jdata数据集跑出来HR10也不到0.4

**Comment by MingshiYan** [comment]
我找不到原始log日志了，你试试grid search，把lr设置小一点试试（大概从1e-5,1e-4开始搜索）

**Comment by 0yuanxi0** [comment]
好的谢谢！
